# must specify
model: multistage_trainer.model.TrainModel
iterator: multistage_trainer.model.Trainer
dataset: multistage_trainer.data.Dataset_MNIST

batch_size: 28
num_steps: 501
lr : 1.0e-4  # yaml needs 1.0 for exponential notation
lr_decay_begin : 100 # TODO remove these in future versions
lr_decay_end : 1001  # TODO remove these in future versions


# options
spatial_size: 28
log_freq : 10
ckpt_freq : 300
is_train: True
n_processes : 1


# logging options
log_images_to_tensorboard: True


stages:
  1:
    name: pretrain
    end: 250
    losses: []
  2:
    name: train
    losses: ["model"]